### ISSUE TITLE
Python modules Compilation fails

### ISSUE THREAD

**Issue by RDaneelOlivav** [htm-community/htm.core#702]
I'm trying to get the htm-2d-object-modeling example working, which I need the nupic.cpp compiled as far aas I see.
But when I compile I had to Upgrade the CMake to higher than 3.7 and add in /home/rdaneel/RI/nupic.cpp/external/common.cmake the line SET(CMAKE_CXX_FLAGS "-std=c++11 -O3")
to fix error when compiling.

Now when I execute the command:
python setup.py install --user --force

It gives the following error:

> In file included from /home/rdaneel/RI/nupic.cpp/src/htm/algorithms/Connections.cpp:27:0:
/home/rdaneel/RI/nupic.cpp/src/htm/algorithms/Connections.hpp:602:24: error: enclosing class of constexpr non-static member function ‘htm::Permanence htm::Connections::getConnectedThreshold() const’ is not a literal type
   constexpr Permanence getConnectedThreshold() const noexcept { return connectedThreshold_; }
                        ^

Any ideas? Is there a script to setup and install everything in a virtualenv? I'm trying to make this easy for everyone but as far as I see it seems its not that straightforward.

Any help would be appreciated

EDIT: Ubuntu18.04 build is OK, on Ubuntu 16.04 there are some problems.

**Comment by breznak** [comment]
> and add in /home/rdaneel/RI/nupic.cpp/external/common.cmake the line SET(CMAKE_CXX_FLAGS "-std=c++11 -O3")
to fix error when compiling.

you shouldn't have to do that. I don't know if the subsequent err you're seeing is a cause of externals being forced to c++11, and rest possibly c++17. 

does your code need to be c++11?, htm.core can be both c++11/17. See `CommonCompilerConfig.cmake` file. 

>  and install everything in a virtualenv? 

virtualenv is a good idea, you should set it up yourself, see `python -m venv`. 

> Is there a script to setup

yes, the simple, work-for-all install option is `python setup.py install --user --force `

Let me know if that helps, 
Cheers,

**Comment by RDaneelOlivav** [comment]
Reseted everything from scratch, and at least in a virtual env for pythn 3.7, this errors occues when executing the following command:

> python setup.py install --force

> Scanning dependencies of target common
> [  2%] Building CXX object CMakeFiles/common.dir/common/murmurhash3/MurmurHash3.cpp.o
> In file included from /usr/include/c++/5/cstdint:35:0,
>                  from /home/rdaneel/RI/htm.core/external/common/murmurhash3/MurmurHash3.hpp:23,
>                  from /home/rdaneel/RI/htm.core/external/common/murmurhash3/MurmurHash3.cpp:5:
> /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
> 

Any ideas? Is because I tried to install through binaries and for python 3.7 worked ( 3.6 and 3.5 gave the None error:

(ri_venv3.6) rdaneel (master) htm.core $ python -m pip install -i https://test.pypi.org/simple/ htm.core
Looking in indexes: https://test.pypi.org/simple/
Collecting htm.core
  ERROR: Could not find a version that satisfies the requirement htm.core (from versions: none)
ERROR: No matching distribution found for htm.core

And with 3.7, afterwards in the htm-2d-object gives this wierd error when executing: 

ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/rdaneel/RI/ri_venv3.7/lib/python3.7/site-packages/htm/bindings/algorithms.cpython-37m-x86_64-linux-gnu.so)

Any ideas?

**Comment by breznak** [comment]
> 3.6 and 3.5 gave the None error: 

this is expected, for now `pip` requires python3.7 for htm.core

> /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

it looks like you're using some old compiler? What's your OS, compiler? 

> Is because I tried to install through binaries and for python 3.7 worked 

any problem? can you work with the py3.7 binaries, then?

**Comment by RDaneelOlivav** [comment]
Hi, thanks for the fats answers. Lets go by parts:

> any problem? can you work with the py3.7 binaries, then?

So binaries afterwards seem to give me some issues when executing htm-2d-object-modeling git, I executed the python/main.py and got this error:

    (ri_venv3.7) rdaneel (master) python $ python main.py
    Traceback (most recent call last):
    File "main.py", line 14, in
    from htm.bindings.algorithms import SpatialPooler
    ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/rdaneel/RI/ri_venv3.7/lib/python3.7/site-packages/htm/bindings/algorithms.cpython-37m-x86_64-linux-gnu.so)


> it looks like you're using some old compiler? What's your OS, compiler?

Let me give you some details, if you need something specific please tel mee how to retrieve that info so we can solve the issue faster:

$ rdaneel ~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

$ /usr/bin/cmake --version
cmake version 3.5.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).

I installed also other versions of cmake, but it seems this is the one set by default.

So I really dont know what the issue there, because I cant compile it manually ( thinking that the issue in the 2D objects git is due to some strange compilation in the binaries ) and I cant use the binaries either... Any ideas?

**Comment by breznak** [comment]
> ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/rdaneel/RI/ri_venv3.7/lib/python3.7/site-packages/htm/bindings/algorithms.cpython-37m-x86_64-linux-gnu.so)
 

this is likely because the glibc on your machine is older than the one at compiler (CI) machine. @dkeeney I thought we link `stdlibc++` statically, and that that would be enough, not causing this problem? 
Sorry, we got to build the `pip` packages only recently and the process is not fine-tuned yet. 

> I installed also other versions of cmake, but it seems this is the one set by default.

Please see details for the minimal versions of software in Readme, for cmake I think it's 3.7/3.8 at least? (3.10 works fine), and same for gcc/g++ , you need one with c++11/17 support (currently, compilers with c++17 are tested), Python (3.7.5+, 2.7 might work, no guarantee)

**Comment by breznak** [comment]
please also post versions of python, g++

**Comment by RDaneelOlivav** [comment]
(ri_venv3.7) rdaneel RI $ python --version
Python 3.7.4


(ri_venv3.7) rdaneel RI $ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Ok I'll try to set a different CMake version at least 3.10. Same with gcc. The python I think is ok being in a Venv with python 3.7.

Or do you reccomend to just install Ubuntu 18 or higher? Would this probably fix most of these issues?

**Comment by breznak** [comment]
that gcc should be fine, so only the cmake. Let us know. 

> just install Ubuntu 18 or higher? Would this probably fix most of these issues?

I'll try to install on ubuntu16.04 as an excercise for compatibility, but yes, our CI and devs use ubuntu18.04, so that version would be problem free.

**Comment by RDaneelOlivav** [comment]
Ok let me try ASAP

**Comment by RDaneelOlivav** [comment]
> /usr/local/bin/cmake --version
cmake version 3.13.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

> (ri_venv3.7) rdaneel RI $ /usr/bin/cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).


It seems that although I upgraded in Ubuntu to 3.13, the 3.5 is used when executing the command:

> (ri_venv3.7) rdaneel (master) htm.core $ python setup.py install --user --force
Python version: 3.7.4 (default, Sep  2 2019, 20:44:09) 
[GCC 5.4.0 20160609]


Dont know if anyone has any idea of how to fix this without removing every cmake 3.5 instalation ( it affects a lot of systems ).

Otherwise the error continues to appear in the compilation: 

> [  2%] Building CXX object CMakeFiles/common.dir/common/murmurhash3/MurmurHash3.cpp.o
In file included from /usr/include/c++/5/cstdint:35:0,
                 from /home/rdaneel/RI/htm.core/external/common/murmurhash3/MurmurHash3.hpp:23,
                 from /home/rdaneel/RI/htm.core/external/common/murmurhash3/MurmurHash3.cpp:5:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

**Comment by breznak** [comment]
> It seems that although I upgraded in Ubuntu to 3.13, the 3.5 is used when executing the command 

yes, your paths or something is not set up correctly. You can do this though: 
```
cd REPO
mkdir -p build/scripts
cd build/scripts
/usr/local/bin/cmake (the 3.13 ver) ../..
cd ../..
python setup.py install --force
```

> from /home/rdaneel/RI/htm.core/external/common/murmurhash3/MurmurHash3.cpp:5:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

I'll have a look at this

**Comment by RDaneelOlivav** [comment]
I tried changing with the same result.

I then created a VirtualMachine with stock Ubuntu 18 installed and everything worked inside a venv of python 3.7.

**Comment by breznak** [comment]
> with stock Ubuntu 18 installed and everything worked

glad it works for you! 
So the takeaway is, Ubuntu 18.04 is fine, 16.04 is problematic. I don't know if it's worth pursuing 16.04, if there's already another newer LTS, and 20.04 LTS coming soon.

**Comment by RDaneelOlivav** [comment]
I totally agree. We should just state that as requirement Ubuntu 18 minimum and when 20 comes out then work with that ;). Thanks a lot for the help @breznak . Lets see if I can now spend a bit of time getting to know again the htm system and work on the 2d object project ;).
